### ISSUE TITLE
Styles don't match those on OS Zoomstack web page

### ISSUE THREAD

**Issue by robalexclark** [OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets#7]
I've got the geopackage into qgis and applied the QML styles and layers in the correct order. However the styles in this repo don't match those on the OS website, specifically at: [](https://labs.os.uk/prototyping/osel-framework/open-zoomstack/ )

For example there are the following differences:
Fonts - England is in caps on website, lower case in qgis
Font sizes - much smaller on the website
Font colours - pretty sure these are different
Roads - some roads (private?) are dashed on website
Buildings and water - have slight 3d view on website

Is there an update in the works to this repo that will synchronise the styles to match the website version?

**Comment by charleyglynn** [comment]
Hi @robalexclark When you say 'on the OS website' can I just check that you're referring to the map demo on this page: https://www.ordnancesurvey.co.uk/business-government/products/open-zoomstack ?

**Comment by robalexclark** [comment]
Yes (sorry for not being clear). I should have also mentioned that I am looking at the Outdoor style at this time (although other styles might not match either).

For comparison my zoomstack map is at [https://test.floodassist.co.uk/flood-warnings/map](https://test.floodassist.co.uk/flood-warnings/map ), so you can see the differences in fonts at the low zoom levels. 

Note that  zoom levels >14 are not yet there - still rendering! :-)  However previewing in QGIS shows that there are no 3d effects to buildings and water.

**Comment by egil1978** [comment]
Hi @robalexclark 
You are right. There are a few anomalies from the style represented in the demo on the OS Zoomstack homepage against the stylesheets released with the data. Some of the points you have raised we are aware of and we will amend these within the QML files as soon as possible. To address your points directly,

**Fonts - England is in caps on website, lower case in qgis**
This will be updated within the stylesheets
 
**Font sizes - much smaller on the website**
There will be noticeable subtle differences due to the different software we use and the way we deal with scale ranges. You can of course change these font sizes within the software to suite your needs.
 
**Font colours - pretty sure these are different**
This will be updated within the stylesheets
 
**Roads - some roads (private?) are dashed on website**
This will be updated within the stylesheets
 
**Buildings and water - have slight 3d view on website**
The demo was made using Mapbox GL JS where we included a 3D effect to the buildings. The decision was made not to include this as part of the stylesheets but rather leave this decision down to the user themselves. You can apply a 3rd dimension to your buildings in QGIS using the [Qgis2threejs](https://plugins.qgis.org/plugins/Qgis2threejs/) plugin.
Hope this helps. Ill aim to get the stylesheets updated as soon as possible.

**Comment by robalexclark** [comment]
Hi,

Any news on when these stylesheets are likely to be updated - mainly so I can decide whether to begin another month long render process now or hold off until later.

Thanks.

**Comment by egil1978** [comment]
Hi Robin,
If I found some time to look at the Outdoor style next week would that work for you?

Thanks.

**Comment by robalexclark** [comment]
That would be wonderful - thank you! :-)

**Comment by egil1978** [comment]
Hi Robin, I have amended the QML files for all QML style's so they are now aligned to the demo you refer to.

- Country names are now in caps
- Font colours match demo
- Restricted roads are now pecked

Let me know if you are happy with the amends and close this issue down.

Thanks

Paul.

**Comment by robalexclark** [comment]
Hi Paul,

Just checked it out - looks great - thanks once again!
